### ISSUE TITLE
workspace外のファイルを使った場合の対応を考える

### ISSUE THREAD

**Issue by yasuraok** [yasuraok/SimpleTextRefine#1]
LLM応答をファイルに書き出してdiffとして表示するために、現状では.vscode以下に元ファイルと同様の相対パスのところにLLM応答を書き出している。workspace外のファイルだとパスが分からない。

- 案1: 単純にエラーにする
- 案2: workspace外のファイルの場合、元パスに依存しない.vscode以下のパスを用意し、そこにLLM応答を書き出してdiff表示をする

そもそもとして、LLM応答を書き出すファイルの置き場所の条件は主に以下3つ。これを満たしさえすれば案2はどういう実装でもよい
- 複数ファイルを開いたときに衝突しない
- どの元ファイルとLLM応答ファイルが対応するのかが人間に分かる
- 一か所に集まっている (git ignoreしやすい)

**Comment by shimajima-eiji** [comment]
問題は

> workspace外のファイルだとパスが分からない。

だと思うので、これも Prompt_path同様に設定側で指定するか、あるいはPrompt_pathに指定した場所に`.simple_text_refine_cache` を作るのではダメですかね？
Prompt_pathが設定されてない場合は現状通りエラー吐いていいと思いました。


コードで関連しそうなのは以下ですかね？

- https://github.com/yasuraok/SimpleTextRefine/blob/8cf4ced55dbc67fd29bbf2bd8eec76c3c0f3d29b/prg/prompt.js#L24-L44
- https://github.com/yasuraok/SimpleTextRefine/blob/8cf4ced55dbc67fd29bbf2bd8eec76c3c0f3d29b/prg/extension.js#L55-L63

**Comment by yasuraok** [comment]
> Prompt_pathが設定されてない場合は現状通りエラー吐いていいと思いました。

https://github.com/yasuraok/SimpleTextRefine/pull/14#issue-2305085747 に書いた通り、空プロンプト + appendならこの条件でも続行可能なので、そのようにしてみた。
こうやってどんどんエラー中断自体を減らしていきたい。

**Comment by shimajima-eiji** [comment]
内容が多いので（後で読み直した時に間違えないように）現状版を転記しておきます。最新は↑のコメント内リンクから

> workspace未設定のファイルの場合
output.type == append の場合、現在編集中のエディタに直接応答を書き込むので、workspace未選択でprompt pathやcache pathが定まらない場合でもシステムプロンプトなしでLLM呼び出しをすることが可能になる。
そこで、workspace未選択 (かつdefault prompt path未設定) の場合の挙動を改善する。
>
> before: エラーを吐いて諦める
after: システムプロンプトなし、output.type == appendでLLMを呼び出す

全体設計として

> エラー中断自体を減らしていきたい

が大事なポイントだと思いました！
この方針はいいと思います！

**Comment by shimajima-eiji** [comment]
@yasuraok 
以下で解決済みっぽいIssueの整理をしてます

- #14 

---

本件のクローズ要件がわかってないですが、個人的にはタイトルの「workspace外のファイルを使った場合の対応を考える」について前向きに対応する方針で進めてるように見えるので、タイトルのままであれば解決かなーと思ってます

**Comment by yasuraok** [comment]
ゴールとしては「workspace未設定・カスタムプロンプトパス設定なしの場合にプロンプトファイルをどこで管理するかを決め、エラーが出ないようする」でしたが、ノープロンプトでも警告を出しつつ動くようにしたので、優先度はさがりました。次にこの近辺をいじる時は目的感が変わっている気がするので、別issueになると想定して、これはクローズしちゃいます。
