### ISSUE TITLE
README更新：Ver0.0.7 -> 0.0.8の変更点をまとめる

### ISSUE THREAD

**Issue by shimajima-eiji** [yasuraok/SimpleTextRefine#17]
Ver7とVer8の差分が結構多そうなので、いったんここでまとめさせてください
（他のコミッターを増やして盛り上げたい気持ち）

**Comment by yasuraok** [comment]
多謝。いちおう、プルリクのdescriptionがなるべくそのままREADMEに使えるようなつもりで書いています…。

https://github.com/yasuraok/SimpleTextRefine/pull/14#issue-2305085747

**Comment by yasuraok** [comment]
pre-releaseを出そうと思ってますが、[こんな理由により](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions) pre-releaseはver. 0.1.0 になる必要がありそうですw そして正式リリースは0.1.1になる…

**Comment by shimajima-eiji** [comment]
本Issueの目的は「README更新：Ver0.0.7 -> 0.0.8の変更点をまとめる」で、既にまとまってるので何もせずCloseします
古いIssueが残り続けて管理されてない、みたいになるのはどうかなと思うので、Readmeを更新するタスクは別途対応にしましょう
