### ISSUE TITLE
#4 【要確認・優先度低？】Release機能使う際の、ビルドどうするか問題を考える

### ISSUE THREAD

**Issue by shimajima-eiji** [yasuraok/SimpleTextRefine#8]
- 現状はローカルでビルドを実施。そもそも、個人開発なのでCIレベルでは不要だった
- CI(GitHub Actions)でもできるし、rc(x)を作るならマーケットプレイスには上がらないので、デバッグを求める際は検証用のvsixファイルは欲しい

_Originally posted by @shimajima-eiji in
- https://github.com/yasuraok/SimpleTextRefine/issues/4#issuecomment-2105526793_

**Comment by shimajima-eiji** [comment]
クローズ要件：いるかいらないかだけ判断して回答がえられればOK。やる場合は別タスクで起票する

**Comment by yasuraok** [comment]
少し管理体制を真面目にして、devブランチを導入、これをdefaultブランチに設定しました。またCIをいれて、全pushに対してvsixを作るようにしました (コミットハッシュがバージョン番号に入っている)

したがって、以下のような運用になりそうです。

### リリースまでの流れ
- devブランチにあるものをrc版としてGitHub上ではReleaseに設置する。そこで更新履歴を整理する (READMEも整理できるとよい)
- このrc版のvsixをVSCode Marketplace にてpreviewバージョンとして投稿する。そうするとエディタ側でpreviewを追従する設定にしておくとrc版が使えるようになる。previewバージョンの設定の仕方をまだ知らないが、難しくはないだろう
- rc版に対して回帰チェックをする。それをパスしたらmainにマージ & 正式版としてmarketplaceに公開

### 回帰チェック項目の案
- 基本動作
  - GPTとClaudeのそれぞれで文章生成ができる
- 初期セットアップの確認
  - 各種設定を全て削除し、新しいworkspaceを開いて、Call LLM with selected text ...を叩く。API Keyが無くて怒られ、setting画面に行ける
  - API Keyをセットした後にリトライし、promptが無いと怒られ、ひな型からファイルを作成できる
- アドバンスド機能
  - output.typeの選択肢それぞれが機能する refs #14 
  - カスタムプロンプト機能が機能する refs #4

**Comment by yasuraok** [comment]
以下まで作ってしまいました。

- devブランチのCIを[手動で叩くと](https://qiita.com/SnowCait/items/7a30ff80be70a739915c)pre-releaseとしてマーケットプレイスに出る
- mainブランチのCIを手動で叩くとreleaseとしてマーケットプレイスに出る

これまで通りfeatureブランチではvsixがartifactとして残るので、それを手動インストールも可能。

というわけで、Releaseの作業自体はこれで完成かなと思います。更新履歴をまとめたりそれをGitHib Releaseとして掲載したりと言うのをどのタイミングでどういう形式でやるのが一番簡単かを考えるのは継続。

**Comment by shimajima-eiji** [comment]
タスクとしてやると重たいかな？と思っていたので、もともとは検討するだけのIssueだったんですが全部解決した気がしますね、さすがです！
このIssueでやるべきはタイトルの通り「Release機能使う際の、ビルドどうするか問題を考える」だったので、本件は解決済みとしてクローズします！

---

> 更新履歴をまとめたりそれをGitHib Releaseとして掲載したり

タスク管理が煩雑になるので、これらは別タスクとして扱いましょうか。Issue作っておきます。
